server:
  port: 17812
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
