spring:
  application:
    name: gateway-service
server:
  port: 10093
knife4j:
  gateway:
    enabled: true
    strategy: manual
    routes:
      - name: 用户服务
        service-name: user-service
        url: /v3/api-docs/default
        context-path: /
      - name: 订单服务
        service-name: order-service
        url: /v3/api-docs/default
        context-path: /