
knife4j:
  enable: true
  documents:
    -
      group: 2.X版本
      name: 另外文档分组请看这里
      locations: classpath:markdown/*
    -
      group: 3.默认接口
      name: 我是另外一个分组的文档
      locations: classpath:markdown/*
  setting:
    language: zh-CN
    enableSwaggerModels: true
    enableDocumentManage: true
    swaggerModelName: 实体类列表
    enableVersion: true
    enableReloadCacheParameter: false
    enableAfterScript: true
    enableFilterMultipartApiMethodType: POST
    enableFilterMultipartApis: true
    enableRequestCache: true
    enableHost: false
    enableHostText: 192.168.0.193:8000
    enableHomeCustom: false
    homeCustomLocation: classpath:markdown/home.md
    enableSearch: false
    enableFooter: true
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0 | Copyright  2019-[浙江八一菜刀股份有限公司](https://gitee.com/xiaoym/knife4j)
    enableDynamicParameter: true
    enableDebug: true
    enableOpenApi: false
    enableGroup: true
    enableResponseCode: false
  cors: false
  production: false
  basic:
    enable: false
    username: test
    password: 12313
  customCode: 200
server:
  port: 8990
#spring:
 # mvc:
  #  pathmatch:
      #matching-strategy: ant_path_matcher
