
server:
  port: 8990
#spring:
 # mvc:
  #  pathmatch:
      #matching-strategy: ant_path_matcher
  servlet:
    context-path: /
knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: "`我是测试`,**你知道吗**
    # aaa"
    email: xiaoymin@foxmail.com
    concat: 八一菜刀
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: com.focus
        api-rule: package
        api-rule-resources:
          - com.knife4j.demo.new3
      test:
        group-name: 根据包名
        api-rule: package
        basic-auths:
          - key-name: MyAuthorization
            name: Authorization
            auth-type: API_KEY
            paths:
              - /**
        api-rule-resources:
          - com.knife4j.demo.new3
      path:
        group-name: 根据路由
        path-rule: ant
        path-rule-resources:
          - /job/**
          - /work/**
          - /job1/**
        oauth2:
          grant-type: password
          paths:
            - /**
          config:
            url: http://127.0.0.1:8080/token/oauth
            token-name: access_name
            client-id: 123
            client-secret: abc
          scopes:
            - name: read
              description: read resource
            - name: write
              description: write resources
      regex:
        group-name: 根据正则表达式
        path-rule: regex
        path-rule-resources:
          - .*?work.*
      annotation:
        group-name: 根据注解
        api-rule: annotation
        api-rule-resources:
          - io.swagger.annotations.ApiOperation
  production: false
  setting:
    custom-code: 500
    enable-footer-custom: false
    footer-custom-content: 我是自定义的Footer
    language: zh_cn
    enable-footer: true
    enable-debug: true
    enable-open-api: true
    enable-host: false
    enable-host-text: localhost:9090
  documents:
    - name: 我测试
      group: 根据包名
      locations: classpath:markdown/*
  basic:
    enable: false
    username: abc
    password: 123
  cors: true
spring:
  messages:
    basename: i18n/message
    encoding: utf-8
    cache-duration: 3600
